image: trion/ng-cli-karma

cache:
  paths:
    - node_modules/

deploy_stage:
  stage: deploy
  environment: Stage
  only:
    - master
  script:
    - rm ./package-lock.json
    - npm install
    #- ./node_modules/@angular/cli/bin/ng test --progress false --single-run=true --watch=false
    #- ./node_modules/@angular/cli/bin/ng e2e --progress false --watch=false
    - ./node_modules/@angular/cli/bin/ng build --progress false --prod --base-href surveyadmin-stage.surge.sh
    - ./node_modules/.bin/surge -p dist/ --domain surveyadmin-stage.surge.sh

deploy_production:
  stage: deploy
  environment: Production
  only:
    - tags
  script:
    - rm ./package-lock.json
    - npm install
    #- ./node_modules/@angular/cli/bin/ng test --progress false --single-run=true  --watch=false
    #- ./node_modules/@angular/cli/bin/ng e2e --progress false --watch=false
    - ./node_modules/@angular/cli/bin/ng build --progress false --prod --base-href surveyadmin.surge.sh
    - ./node_modules/.bin/surge -p dist/ --domain surveyadmin.surge.sh


#commands
#node_modules/.bin/surge login
#ng build --prod --aot
#./node_modules/.bin/surge -p dist/ --domain XXX-stage.surge.sh